apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: payment-watchdog-ui
  # namespace: staging  # Removed - let overlays control namespace

resources:
- service-account.yaml
- configmap.yaml
- secret.yaml
- service.yaml
- deployment.yaml

labels:
  - pairs:
      app: payment-watchdog
      component: ui
      version: v1.0.0
    includeSelectors: false
    includeTemplates: true

images:
- name: payment-watchdog-ui
  newName: ghcr.io/sambitmohanty1/payment-watchdog/web
  newTag: latest
