apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexure-postgres
spec:
  template:
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: postgres
          securityContext:
            runAsUser: 999
            runAsGroup: 999
