apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-watchdog-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: payment-watchdog-api
  namespaceSelector:
    matchNames:
      - lexure
  endpoints:
  - port: 8080
    interval: 15s
    path: /metrics
    scheme: http
