apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Import base components and applications from the main repo
resources:
  - ../../../api/deployments/kubernetes/base/components/postgres
  - ../../../api/deployments/kubernetes/base/components/redis
  - ../../../api/deployments/kubernetes/apps/payment-watchdog-api
  - ../../../api/deployments/kubernetes/apps/payment-watchdog-web
  - ingress.yaml
  - secret.yaml
  - cluster-issuer.yaml

# Provide patches for arm64 node selection or resource limits if necessary
# patches:
#   - path: patch-node-selector.yaml

# Namespace
namespace: payment-watchdog

images:
  - name: ghcr.io/sambitmohanty1/payment-watchdog-api
    newName: ghcr.io/sambitmohanty1/payment-watchdog-api
    newTag: latest
  - name: ghcr.io/sambitmohanty1/payment-watchdog-web
    newName: ghcr.io/sambitmohanty1/payment-watchdog-web
    newTag: latest
