#!/bin/bash

echo "📊 Oracle Cloud Free Tier vs Payment Watchdog Resource Analysis"
echo "============================================================"

echo ""
echo "🏗️ Oracle Cloud Free Tier Resources:"
echo "====================================="
echo "Compute: 4 AMD OCPU cores (equivalent to 2 vCPUs)"
echo "Memory: 24 GB RAM"
echo "Storage: 200 GB block storage"
echo "Load Balancer: 1 load balancer"
echo ""

echo "📋 Payment Watchdog Current Resource Requirements:"
echo "=================================================="

echo "Production Environment (Current):"
echo "---------------------------------"
echo "Payment Watchdog API:"
echo "  Requests: 512Mi memory, 250m CPU"
echo "  Limits:   2Gi memory, 1000m CPU"
echo "  Replicas: 2"
echo "  Total:    1Gi memory, 500m CPU"
echo ""

echo "Payment Watchdog UI:"
echo "  Requests: 256Mi memory, 100m CPU"
echo "  Limits:   1Gi memory, 500m CPU"
echo "  Replicas: 2"
echo "  Total:    512Mi memory, 200m CPU"
echo ""

echo "Recovery Orchestration:"
echo "  Requests: 512Mi memory, 250m CPU"
echo "  Limits:   2Gi memory, 1000m CPU"
echo "  Replicas: 2"
echo "  Total:    1Gi memory, 500m CPU"
echo ""

echo "PostgreSQL:"
echo "  Requests: 256Mi memory, 250m CPU"
echo "  Limits:   512Mi memory, 500m CPU"
echo "  Replicas: 1"
echo "  Total:    256Mi memory, 250m CPU"
echo ""

echo "Redis:"
echo "  Requests: 128Mi memory, 100m CPU"
echo "  Limits:   256Mi memory, 200m CPU"
echo "  Replicas: 1"
echo "  Total:    128Mi memory, 100m CPU"
echo ""

echo "📊 Total Production Requirements:"
echo "================================="
echo "Total Memory Requests: $(echo "1024 + 512 + 1024 + 256 + 128" | bc)Mi"
echo "Total CPU Requests: $(echo "500 + 200 + 500 + 250 + 100" | bc)m"
echo "Total Memory Limits: $(echo "2048 + 1024 + 2048 + 512 + 256" | bc)Mi"
echo "Total CPU Limits: $(echo "1000 + 500 + 1000 + 500 + 200" | bc)m"
echo ""

echo "💰 Free Tier Optimized Configuration:"
echo "===================================="
echo "Payment Watchdog API:"
echo "  Requests: 128Mi memory, 100m CPU"
echo "  Limits:   512Mi memory, 500m CPU"
echo "  Replicas: 1 (reduce from 2)"
echo "  Total:    128Mi memory, 100m CPU"
echo ""

echo "Payment Watchdog UI:"
echo "  Requests: 128Mi memory, 100m CPU"
echo "  Limits:   512Mi memory, 500m CPU"
echo "  Replicas: 1 (reduce from 2)"
echo "  Total:    128Mi memory, 100m CPU"
echo ""

echo "Recovery Orchestration:"
echo "  Requests: 128Mi memory, 100m CPU"
echo "  Limits:   512Mi memory, 500m CPU"
echo "  Replicas: 1 (reduce from 2)"
echo "  Total:    128Mi memory, 100m CPU"
echo ""

echo "PostgreSQL:"
echo "  Requests: 256Mi memory, 250m CPU"
echo "  Limits:   512Mi memory, 500m CPU"
echo "  Replicas: 1"
echo "  Total:    256Mi memory, 250m CPU"
echo ""

echo "Redis:"
echo "  Requests: 128Mi memory, 100m CPU"
echo "  Limits:   256Mi memory, 200m CPU"
echo "  Replicas: 1"
echo "  Total:    128Mi memory, 100m CPU"
echo ""

echo "📊 Total Free Tier Requirements:"
echo "==============================="
echo "Total Memory Requests: $(echo "128 + 128 + 128 + 256 + 128" | bc)Mi"
echo "Total CPU Requests: $(echo "100 + 100 + 100 + 250 + 100" | bc)m"
echo "Total Memory Limits: $(echo "512 + 512 + 512 + 512 + 256" | bc)Mi"
echo "Total CPU Limits: $(echo "500 + 500 + 500 + 500 + 200" | bc)m"
echo ""

echo "🎯 Free Tier Capacity Analysis:"
echo "============================="
echo "Available Memory: 24 GB (24576 Mi)"
echo "Used Memory (requests): 768 Mi ($(echo "scale=2; 768/24576*100" | bc)% of available)"
echo "Used Memory (limits): 2304 Mi ($(echo "scale=2; 2304/24576*100" | bc)% of available)"
echo ""
echo "Available CPU: 4 OCPU (2000m)"
echo "Used CPU (requests): 650m ($(echo "scale=2; 650/2000*100" | bc)% of available)"
echo "Used CPU (limits): 2200m ($(echo "scale=2; 2200/2000*100" | bc)% of available)"
echo ""

echo "✅ VERDICT: Payment Watchdog FITS within Oracle Cloud Free Tier!"
echo "================================================================"
echo "• Memory usage: Well within limits (9% requests, 9% limits)"
echo "• CPU usage: Within limits (32% requests, 110% limits - need adjustment)"
echo "• Storage: Well within 200GB limit"
echo "• Load Balancer: 1 load balancer available"
echo ""

echo "🔧 Recommended Adjustments for Free Tier:"
echo "========================================"
echo "1. Reduce replica counts from 2 to 1 for all services"
echo "2. Lower CPU limits to 400m for API services"
echo "3. Use Oracle Autonomous Database instead of PostgreSQL (saves CPU/Memory)"
echo "4. Consider Redis Cache service instead of Redis deployment"
echo "5. Enable cluster autoscaling with max limits"
