apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  labels:
    app: cloudflare-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      containers:
      - name: tunnel
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - "--no-autoupdate"
        - run
        - "--token"
        - "REPLACE_WITH_YOUR_CLOUDFLARE_TOKEN"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
