apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  labels:
    app: cloudflare-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      containers:
      - name: tunnel
        image: docker.io/cloudflare/cloudflared:latest
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-tunnel-secret
              key: tunnel-token
        args:
        - tunnel
        - "--no-autoupdate"
        - run
        - "--token"
        - "$(TUNNEL_TOKEN)"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
