apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  labels:
    app.kubernetes.io/part-of: payment-watchdog
    environment: sovereign-au
data:
  namespace: sovereign-au
  environment: sovereign-au
  data_residency: australia
  # Database connection variables
  POSTGRES_SERVICE_NAME: postgres-sovereign-au
  POSTGRES_SERVICE_PORT: "5432"
  NAMESPACE: sovereign-au
