apiVersion: v1
kind: Service
metadata:
  name: recovery-orchestration
  labels:
    app.kubernetes.io/name: recovery-orchestration
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: payment-watchdog
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app.kubernetes.io/name: recovery-orchestration
