apiVersion: v1
kind: ServiceAccount
metadata:
  name: recovery-orchestration
  labels:
    app.kubernetes.io/name: recovery-orchestration
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: payment-watchdog
  annotations:
    iam.amazonaws.com/role: "payment-watchdog-worker-role"
