apiVersion: v1
kind: Service
metadata:
  name: payment-watchdog-web
  labels:
    app.kubernetes.io/name: payment-watchdog-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: payment-watchdog
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app.kubernetes.io/name: payment-watchdog-web
