apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-watchdog-api
spec:
  template:
    spec:
      containers:
      - name: app
        image: ghcr.io/sambitmohanty1/payment-watchdog/api:latest
        imagePullPolicy: Always
