FROM golang:1.23-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache git curl

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN go build -o main cmd/main.go

# Expose port
EXPOSE 8080

# Run the binary
CMD ["./main"]
